[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[mypy]
python_version = "3.11"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"